platform :ios, '15.0'
use_frameworks! :linkage => :static

target 'SimpleMusic' do
  pod 'SnapKit', '~> 5.7'
  pod 'YYKit'
  pod 'IQKeyboardManager', '~> 4.0.13'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
